unit TestPromptArgsFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, TBX, TntButtons, SysUtils, ComCtrls, Windows, StdCtrls, BaseForm, Messages, 
  Menus, Controls, Classes, SpTBXItem, Dialogs, PromptArgsFrm, TB2Item, Forms, Buttons, 
  TntComCtrls, TntStdCtrls, Graphics;
type
  // Test methods for class TfrmPromptArgs
  
  TestTfrmPromptArgs = class(TTestCase)
  strict private
    FfrmPromptArgs: TfrmPromptArgs;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestbtnArgumentsClick;
    procedure TestedArgumentsChange;
    procedure TestArgumentsClick;
    procedure TestEdit;
  end;

implementation

procedure TestTfrmPromptArgs.SetUp;
begin
  FfrmPromptArgs := TfrmPromptArgs.Create(nil);
end;

procedure TestTfrmPromptArgs.TearDown;
begin
  FfrmPromptArgs.Free;
  FfrmPromptArgs := nil;
end;

procedure TestTfrmPromptArgs.TestbtnArgumentsClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmPromptArgs.btnArgumentsClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmPromptArgs.TestedArgumentsChange;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmPromptArgs.edArgumentsChange(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmPromptArgs.TestArgumentsClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmPromptArgs.ArgumentsClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmPromptArgs.TestEdit;
var
  ReturnValue: Boolean;
  OnMacroReplace: TMacroReplaceEvent;
  Args: WideString;
  CmdLine: WideString;
  Title: WideString;
begin
  // TODO: Setup method call parameters
  ReturnValue := FfrmPromptArgs.Edit(Title, CmdLine, Args, OnMacroReplace);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmPromptArgs.Suite);
end.

