unit TestBaseForm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Windows, TntForms, Forms, Dialogs, Controls, Classes, SysUtils, BaseForm, 
  Graphics, Messages;
type
  // Test methods for class TfrmBase
  
  TestTfrmBase = class(TTestCase)
  strict private
    FfrmBase: TfrmBase;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
  end;

implementation

procedure TestTfrmBase.SetUp;
begin
  FfrmBase := TfrmBase.Create(nil);
end;

procedure TestTfrmBase.TearDown;
begin
  FfrmBase.Free;
  FfrmBase := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmBase.Suite);
end.

