unit TestOptionsFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, TntClasses, CheckLst, SysUtils, ComCtrls, Windows, StdCtrls, BaseForm, 
  Messages, TntExtCtrls, ExtCtrls, Controls, Classes, OptionsFrm, Dialogs, AppOptions, Forms, 
  TntComCtrls, TntStdCtrls, Graphics, TntCheckLst;
type
  // Test methods for class TfrmOptions
  
  TestTfrmOptions = class(TTestCase)
  strict private
    FfrmOptions: TfrmOptions;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestchkShowToolTipsClick;
    procedure TestchkReturnToSaveClick;
    procedure TestbtnLanguageClick;
    procedure TestbtnHelpClick;
    procedure TestchkSavePositionClick;
    procedure TestbtnColorsClick;
    procedure TestcbFontsChange;
    procedure TestcbFontSizesChange;
    procedure TestExecute;
  end;

implementation

procedure TestTfrmOptions.SetUp;
begin
  FfrmOptions := TfrmOptions.Create(nil);
end;

procedure TestTfrmOptions.TearDown;
begin
  FfrmOptions.Free;
  FfrmOptions := nil;
end;

procedure TestTfrmOptions.TestchkShowToolTipsClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.chkShowToolTipsClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestchkReturnToSaveClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.chkReturnToSaveClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestbtnLanguageClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.btnLanguageClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestbtnHelpClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.btnHelpClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestchkSavePositionClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.chkSavePositionClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestbtnColorsClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.btnColorsClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestcbFontsChange;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.cbFontsChange(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestcbFontSizesChange;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmOptions.cbFontSizesChange(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmOptions.TestExecute;
var
  ReturnValue: Boolean;
  Options: TAppOptions;
begin
  // TODO: Setup method call parameters
  ReturnValue := FfrmOptions.Execute(Options);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmOptions.Suite);
end.

