unit TestKbdCfgFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, TntForms, KbdCfgFrame, SysUtils, KbdCfgFrm, ComCtrls, Windows, StdCtrls, 
  BaseForm, Messages, Menus, Controls, Classes, Dialogs, TntActnList, Forms, ActnList, Graphics;
type
  // Test methods for class TfrmConfigKbd
  
  TestTfrmConfigKbd = class(TTestCase)
  strict private
    FfrmConfigKbd: TfrmConfigKbd;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFormCreate;
    procedure TestEditShortCuts;
  end;

implementation

procedure TestTfrmConfigKbd.SetUp;
begin
  FfrmConfigKbd := TfrmConfigKbd.Create(nil);
end;

procedure TestTfrmConfigKbd.TearDown;
begin
  FfrmConfigKbd.Free;
  FfrmConfigKbd := nil;
end;

procedure TestTfrmConfigKbd.TestFormCreate;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmConfigKbd.FormCreate(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmConfigKbd.TestEditShortCuts;
var
  ReturnValue: Boolean;
  AActionList: TTntActionList;
begin
  // TODO: Setup method call parameters
  ReturnValue := FfrmConfigKbd.EditShortCuts(AActionList);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmConfigKbd.Suite);
end.

