unit TestColorsFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, ColorsFrm, SysUtils, Windows, StdCtrls, BaseForm, Messages, Variants, 
  Controls, Classes, Dialogs, AppOptions, Forms, TntStdCtrls, ExtCtrls, Graphics;
type
  // Test methods for class TfrmColors
  
  TestTfrmColors = class(TTestCase)
  published
    procedure TestEdit;
  end;

implementation

procedure TestTfrmColors.TestEdit;
var
  ReturnValue: Boolean;
  Options: TAppOptions;
begin
  // TODO: Setup method call parameters
  Options := TAppOptions.Create('');
  try
    ReturnValue := TfrmColors.Edit(Options);
    // TODO: Validate method results
  finally
    Options.Free;
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmColors.Suite);
end.

