unit TestCommentsFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, TntMenus, TranslateFile, TBX, TntComCtrls, CommentsFrm, Forms, SysUtils, 
  ComCtrls, Windows, TransIntf, TB2Item, StdCtrls, BaseForm, Messages, TntActnList, 
  TntExtCtrls, ExtCtrls, Menus, Controls, Classes, SpTBXItem, Dialogs, TntClasses, 
  TntStdActns, StdActns, Buttons, TntButtons, TntStdCtrls, ActnList, Graphics;
type
  // Test methods for class TfrmComments
  
  TestTfrmComments = class(TTestCase)
  strict private
    FfrmComments: TfrmComments;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFormResize;
    procedure TestFormDestroy;
    procedure TestacCloseExecute;
    procedure TestreTranslationChange;
    procedure TestSetComments;
  end;

implementation

procedure TestTfrmComments.SetUp;
begin
  FfrmComments := TfrmComments.Create(nil);
end;

procedure TestTfrmComments.TearDown;
begin
  FfrmComments.Free;
  FfrmComments := nil;
end;

procedure TestTfrmComments.TestFormResize;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmComments.FormResize(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmComments.TestFormDestroy;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmComments.FormDestroy(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmComments.TestacCloseExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmComments.acCloseExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmComments.TestreTranslationChange;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmComments.reTranslationChange(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmComments.TestSetComments;
var
  CommentChars: TTntStrings;
  Item: ITranslationItem;
begin
  // TODO: Setup method call parameters
  FfrmComments.SetComments(Item, CommentChars);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmComments.Suite);
end.

