unit TestFindReplaceFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FindReplaceFrm, Forms, SysUtils, ActnList, Windows, StdCtrls, BaseForm, 
  Messages, ExtCtrls, Menus, Controls, Classes, Dialogs, TntClasses, TntActnList, StdActns, 
  Buttons, TntButtons, TntStdCtrls, Graphics;
type
  // Test methods for class TfrmFindReplace
  
  TestTfrmFindReplace = class(TTestCase)
  strict private
    FfrmFindReplace: TfrmFindReplace;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestcbFindWhatChange;
    procedure TestbtnCloseClick;
    procedure TestbtnFindNextClick;
    procedure TestbtnReplaceClick;
    procedure TestbtnReplaceAllClick;
    procedure TestFormActivate;
    procedure TestFormCreate;
    procedure TestacCutExecute;
    procedure TestacPasteExecute;
    procedure TestacCopyExecute;
    procedure TestacSelectAllExecute;
    procedure TestacUndoExecute;
    procedure TestacCloseExecute;
    procedure TestFormDestroy;
  end;
  // Test methods for class TFindReplace
  
  TestTFindReplace = class(TTestCase)
  strict private
    FFindReplace: TFindReplace;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestExecute;
  end;

implementation

procedure TestTfrmFindReplace.SetUp;
begin
  FfrmFindReplace := TfrmFindReplace.Create(nil);
end;

procedure TestTfrmFindReplace.TearDown;
begin
  FfrmFindReplace.Free;
  FfrmFindReplace := nil;
end;

procedure TestTfrmFindReplace.TestcbFindWhatChange;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.cbFindWhatChange(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestbtnCloseClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.btnCloseClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestbtnFindNextClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.btnFindNextClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestbtnReplaceClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.btnReplaceClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestbtnReplaceAllClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.btnReplaceAllClick(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestFormActivate;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.FormActivate(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestFormCreate;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.FormCreate(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestacCutExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.acCutExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestacPasteExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.acPasteExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestacCopyExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.acCopyExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestacSelectAllExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.acSelectAllExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestacUndoExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.acUndoExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestacCloseExecute;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.acCloseExecute(Sender);
  // TODO: Validate method results
end;

procedure TestTfrmFindReplace.TestFormDestroy;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfrmFindReplace.FormDestroy(Sender);
  // TODO: Validate method results
end;

procedure TestTFindReplace.SetUp;
begin
  FFindReplace := TFindReplace.Create(nil);
end;

procedure TestTFindReplace.TearDown;
begin
  FFindReplace.Free;
  FFindReplace := nil;
end;

procedure TestTFindReplace.TestExecute;
begin
  FFindReplace.Execute;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmFindReplace.Suite);
  RegisterTest(TestTFindReplace.Suite);
end.

