unit TestSuspiciousConfigFrm;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, TntComCtrls, SysUtils, ComCtrls, Windows, StdCtrls, BaseForm, Messages, 
  TntExtCtrls, ExtCtrls, Controls, Classes, Dialogs, AppOptions, Forms, TntStdCtrls, 
  SuspiciousConfigFrm, Graphics;
type
  // Test methods for class TfrmConfigSuspicious
  
  TestTfrmConfigSuspicious = class(TTestCase)
  strict private
    FfrmConfigSuspicious: TfrmConfigSuspicious;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLoadOptions;
    procedure TestSaveOptions;
    procedure TestEdit;
  end;

implementation

procedure TestTfrmConfigSuspicious.SetUp;
begin
  FfrmConfigSuspicious := TfrmConfigSuspicious.Create(nil);
end;

procedure TestTfrmConfigSuspicious.TearDown;
begin
  FfrmConfigSuspicious.Free;
  FfrmConfigSuspicious := nil;
end;

procedure TestTfrmConfigSuspicious.TestLoadOptions;
var
  AppOptions: TAppOptions;
begin
  // TODO: Setup method call parameters
  FfrmConfigSuspicious.LoadOptions(AppOptions);
  // TODO: Validate method results
end;

procedure TestTfrmConfigSuspicious.TestSaveOptions;
var
  AppOptions: TAppOptions;
begin
  // TODO: Setup method call parameters
  FfrmConfigSuspicious.SaveOptions(AppOptions);
  // TODO: Validate method results
end;

procedure TestTfrmConfigSuspicious.TestEdit;
var
  ReturnValue: Boolean;
  AppOptions: TAppOptions;
begin
  // TODO: Setup method call parameters
  ReturnValue := FfrmConfigSuspicious.Edit(AppOptions);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfrmConfigSuspicious.Suite);
end.

